from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPOSITORY_ROOT = Path(
    __file__
).resolve().parents[1]

repository_root_text = str(
    REPOSITORY_ROOT
)

if repository_root_text not in sys.path:
    sys.path.insert(
        0,
        repository_root_text,
    )


from backend.app.gagf.prelive_blind_assessment import (  # noqa: E402
    PreliveScenarioError,
    validate_pre_live_scenario,
)
from backend.app.gagf.prelive_blind_assessment_runner import (  # noqa: E402
    PreliveBlindAssessmentRunner,
)


CONFIRMATION_PHRASE = "EXECUTE PRELIVE"


def load_json_object(
    path: Path,
    *,
    label: str,
) -> dict[str, Any]:
    if not path.is_file():
        raise PreliveScenarioError(
            f"{label} file does not exist: {path}"
        )

    try:
        payload = json.loads(
            path.read_text(
                encoding="utf-8"
            )
        )
    except json.JSONDecodeError as exc:
        raise PreliveScenarioError(
            f"{label} file is invalid JSON: "
            f"{exc.msg}"
        ) from exc

    if not isinstance(
        payload,
        dict,
    ):
        raise PreliveScenarioError(
            f"{label} root must be a JSON object."
        )

    return payload


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run one operator-controlled PRELIVE "
            "blind governance assessment."
        )
    )

    parser.add_argument(
        "--scenario",
        required=True,
        type=Path,
        help=(
            "Blind scenario JSON generated by "
            "an external AI."
        ),
    )

    parser.add_argument(
        "--oracle",
        required=True,
        type=Path,
        help=(
            "Separately sealed oracle JSON."
        ),
    )

    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help=(
            "New or empty output directory."
        ),
    )

    parser.add_argument(
        "--operator",
        default="PRELIVE Human Operator",
        help=(
            "Human operator identity recorded "
            "in the governed rehearsal."
        ),
    )

    return parser


def print_validation(
    scenario: dict[str, Any],
) -> None:
    validation = validate_pre_live_scenario(
        scenario
    )

    print()
    print("PRELIVE-001 BLIND ASSESSMENT")
    print("=" * 36)

    print(
        "Scenario validation......... "
        + (
            "PASS"
            if validation.valid
            else "FAIL"
        )
    )

    print(
        "Evidence events............. "
        f"{validation.summary.event_count}"
    )

    print(
        "Scenario SHA-256............ "
        f"{validation.scenario_sha256 or '-'}"
    )

    if not validation.valid:
        print()

        for issue in validation.issues:
            print(
                f"[{issue.code}] "
                f"{issue.message}"
            )

        raise PreliveScenarioError(
            "Scenario validation failed."
        )


def confirm_execution() -> bool:
    print()
    print(
        "The oracle has NOT been scored yet."
    )
    print(
        "The next step crosses the governed "
        "assessment execution boundary."
    )
    print(
        "External AI has no execution authority."
    )
    print()

    response = input(
        "Type EXECUTE PRELIVE to continue: "
    )

    return (
        response.strip()
        == CONFIRMATION_PHRASE
    )


def print_result(
    result: Any,
) -> None:
    score = result.scoring

    print()
    print("PRELIVE EXECUTION COMPLETE")
    print("=" * 36)

    print(
        "Assessment execution........ COMPLETE"
    )

    print(
        "Repository chain............ "
        + (
            "VERIFIED"
            if result.verification
            .repository_chain_valid
            else "FAILED"
        )
    )

    print(
        "Oracle leakage.............. "
        + (
            "DETECTED"
            if result.verification
            .oracle_leakage_detected
            else "NONE"
        )
    )

    print(
        "Blind verification.......... PASS"
    )

    print()
    print("--- ORACLE UNSEALED ---")
    print()

    print(
        "True positives.............. "
        f"{len(score.true_positives)}"
    )

    print(
        "False positives............. "
        f"{len(score.false_positives)}"
    )

    print(
        "False negatives............. "
        f"{len(score.false_negatives)}"
    )

    print()
    print(
        "Precision................... "
        f"{score.precision:.4f}"
    )

    print(
        "Recall...................... "
        f"{score.recall:.4f}"
    )

    print(
        "F1.......................... "
        f"{score.f1:.4f}"
    )

    print(
        "Exact condition match....... "
        + (
            "YES"
            if score.exact_condition_match
            else "NO"
        )
    )

    if score.event_count_accuracy is not None:
        print(
            "Event-count accuracy........ "
            f"{score.event_count_accuracy:.4f}"
        )

    if score.band_accuracy is not None:
        print(
            "Band accuracy............... "
            f"{score.band_accuracy:.4f}"
        )

    if (
        score.dominant_constraint_match
        is not None
    ):
        print(
            "Dominant constraint match... "
            + (
                "YES"
                if score
                .dominant_constraint_match
                else "NO"
            )
        )

    print()
    print(
        "Output directory............ "
        f"{result.output_directory}"
    )


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        scenario = load_json_object(
            args.scenario,
            label="Scenario",
        )

        oracle = load_json_object(
            args.oracle,
            label="Oracle",
        )

        print_validation(
            scenario
        )

        if not confirm_execution():
            print()
            print(
                "PRELIVE execution cancelled."
            )
            return 2

        result = (
            PreliveBlindAssessmentRunner()
            .run(
                scenario=scenario,
                oracle=oracle,
                output_directory=(
                    args.output
                ),
                operator_id=args.operator,
                execution_confirmed=True,
            )
        )

        print_result(
            result
        )

        return 0

    except PreliveScenarioError as exc:
        print(
            f"PRELIVE ERROR: {exc}",
            file=sys.stderr,
        )

        return 1


if __name__ == "__main__":
    raise SystemExit(
        main()
    )